apiVersion: v1
kind: Pod
metadata:
  generateName: imagescan
spec:
  containers:
  - image: CLAMSCAN_SOURCE_IMAGE
    imagePullPolicy: Always
    name: imagescan
    env:
    - name: TARGET_IMAGE
      value: CLAMSCAN_TARGET_IMAGE
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /secrets/docker
      name: dockercfg
      readOnly: true
    - mountPath: /var/run/docker.sock
      name: docker-socket
  restartPolicy: Never
  volumes:
  - name: dockercfg
    secret:
      defaultMode: 420
      secretName: default-dockercfg-3dmd8
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
